// src/components/common/editor/LineNumbers.tsx
import type React from "react";
import "./LineNumbers.scss";

interface LineNumbersProps {
	lineCount: number;
}

export const LineNumbers: React.FC<LineNumbersProps> = ({ lineCount }) => {
    return (
        <div className="line-numbers">
            {Array.from({ length: lineCount }, (_, index) => (
                <div key={`line-${index + 1}`}>{index + 1}</div>
            ))}
        </div>
    );
};

// src/components/LineNumbers/LineNumbers.svelte
<script lang="ts">
import { onMount } from "svelte";
import { lineNumbers } from "../../stores/elements";
import "./LineNumbers.scss";

export let lineCount: number;
let _lineNumbers: HTMLDivElement;

onMount(() => {
	lineNumbers.set(_lineNumbers);
});
</script>
  
<div class="line-numbers" bind:this={_lineNumbers}>
    {#each Array(lineCount).fill(0) as _, index}
        <div>{index + 1}</div>
    {/each}
</div>
