// src/components/common/editor/StatusPane.tsx
import React from "react";
import "./StatusPane.scss";

interface StatusPaneProps {
	lineNumber: number;
	char: number;
}

const StatusPane: React.FC<StatusPaneProps> = ({ lineNumber, char }) => {
	return <div className="status-pane">Ln {lineNumber}, Col {char}</div>;
};

export default React.memo(StatusPane);

// src/renderer/src/components/StatusPane/StatusPane.tsx
import type { Editor } from "@renderer/models/Editor";
import type { Accessor, Component } from "solid-js";
import styles from "./StatusPane.module.scss";

interface StatusPaneProps {
	editor: Accessor<Editor>;
}

const StatusPane: Component<StatusPaneProps> = (props) => {
	return (
		<div class={styles["status-pane"]}>
			Ln {props.editor().cursorAt(0).line + 1}, Col{" "}
			{props.editor().cursorAt(0).character + 1}
		</div>
	);
};

export default StatusPane;
