// src/components/StatusPane/StatusPane.svelte
<script lang="ts">
import type { Selection } from "../../models/Selection";
import "./StatusPane.scss";

export let lineNumber: number;
export let char: number;
export let selection: Selection;
</script>
  
<div class="status-pane">
    Ln {lineNumber}, Col {char} 
    {#if selection.getSelectionStart() !== selection.getSelectionEnd()}
        ({selection.getContent().length} selected)
    {/if}
</div>

// src/components/common/editor/StatusPane.tsx
import React from "react";
import type { Selection } from "../../../model/selectionModel";
import "./StatusPane.scss";

interface StatusPaneProps {
	lineNumber: number;
	char: number;
	selection: Selection;
}

const StatusPane: React.FC<StatusPaneProps> = ({
	lineNumber,
	char,
	selection,
}) => {
	return (
		<div className="status-pane">
			Ln {lineNumber}, Col {char}{" "}
			{selection.startIndex !== selection.endIndex
				? `(${selection.content.length} selected)`
				: ""}
		</div>
	);
};

export default React.memo(StatusPane);
